module.exports = [
	{ name: 'Genesis', aliases: [ 'Gen' ] },
	{ name: 'Exodus', aliases: [ 'Exod', 'Ex', 'Exo' ] },
	{ name: 'Leviticus', aliases: [ 'Lev' ] },
	{ name: 'Numbers', aliases: [ 'Num' ] },
	{ name: 'Deuteronomy', aliases: [ 'Deut' ] },
	{ name: 'Joshua', aliases: [ 'Josh' ] },
	{ name: 'Judges', aliases: [ 'Judg' ] },
	{ name: 'Ruth', aliases: [ ] },
	{ name: '1 Samuel', aliases: [ '1 Sam' ] },
	{ name: '2 Samuel', aliases: [ '2 Sam' ] },
	{ name: '1 Kings', aliases: [ '1 Kgs' ] },
	{ name: '2 Kings', aliases: [ '2 Kgs' ] },
	{ name: '1 Chronicles', aliases: [ '1 Chr' ] },
	{ name: '2 Chronicles', aliases: [ '2 Chr' ] },
	{ name: 'Ezra', aliases: [ 'Ezra' ] },
	{ name: 'Nehemiah', aliases: [ 'Neh' ] },
	{ name: 'Esther', aliases: [ 'Esth', 'Est' ] },
	{ name: 'Job', aliases: [ ] },
	{ name: 'Psalms', aliases: [ 'Ps' ] },
	{ name: 'Proverbs', aliases: [ 'Prov', 'Pro' ] },
	{ name: 'Ecclesiastes', aliases: [ 'Eccl', 'Ecc' ] },
	{ name: 'Song of Solomon', aliases: [ 'Song', 'Song of Songs' ] },
	{ name: 'Isaiah', aliases: [ 'Isa' ] },
	{ name: 'Jeremiah', aliases: [ 'Jer' ] },
	{ name: 'Lamentations', aliases: [ 'Lam' ] },
	{ name: 'Ezekiel', aliases: [ 'Ezek' ] },
	{ name: 'Daniel', aliases: [ 'Dan' ] },
	{ name: 'Hosea', aliases: [ 'Hos' ] },
	{ name: 'Joel', aliases: [ ] },
	{ name: 'Amos', aliases: [ ] },
	{ name: 'Obadiah', aliases: [ 'Obad', 'Oba' ] },
	{ name: 'Jonah', aliases: [ 'Jon' ] },
	{ name: 'Micah', aliases: [ 'Mic' ] },
	{ name: 'Nahum', aliases: [ 'Nah' ] },
	{ name: 'Habakkuk', aliases: [ 'Hab' ] },
	{ name: 'Zephaniah', aliases: [ 'Zeph' ] },
	{ name: 'Haggai', aliases: [ 'Hag' ] },
	{ name: 'Zechariah', aliases: [ 'Zech' ] },
	{ name: 'Malachi', aliases: [ 'Mal' ] },

	{ name: 'Matthew', aliases: [ 'Matt' ] },
	{ name: 'Mark', aliases: [ ] },
	{ name: 'Luke', aliases: [ ] },
	{ name: 'John', aliases: [ ] },
	{ name: 'Acts', aliases: [ ] },
	{ name: 'Romans', aliases: [ 'Rom' ] },
	{ name: '1 Corinthians', aliases: [ '1 Cor' ] },
	{ name: '2 Corinthians', aliases: [ '2 Cor' ] },
	{ name: 'Galatians', aliases: [ 'Gal' ] },
	{ name: 'Ephesians', aliases: [ 'Eph' ] },
	{ name: 'Philippians', aliases: [ 'Phil' ] },
	{ name: 'Colossians', aliases: [ 'Col' ] },
	{ name: '1 Thessalonians', aliases: [ '1 Thess' ] },
	{ name: '2 Thessalonians', aliases: [ '2 Thess' ] },
	{ name: '1 Timothy', aliases: [ '1 Tim' ] },
	{ name: '2 Timothy', aliases: [ '2 Tim' ] },
	{ name: 'Titus', aliases: [ ] },
	{ name: 'Philemon', aliases: [ 'Phlm' ] },
	{ name: 'Hebrews', aliases: [ 'Heb' ] },
	{ name: 'James', aliases: [ 'Jas' ] },
	{ name: '1 Peter', aliases: [ '1 Pet' ] },
	{ name: '2 Peter', aliases: [ '2 Pet' ] },
	{ name: '1 John', aliases: [ ] },
	{ name: '2 John', aliases: [ ] },
	{ name: '3 John', aliases: [ ] },
	{ name: 'Jude', aliases: [ ] },
	{ name: 'Revelation', aliases: [ 'Rev' ] },
]
